app_oauth2_dropbox:
    path:     /oauth2/dropbox
    defaults: { _controller: AppBundle:OAuth2:dropbox }

app_oauth2_dropbox_complete:
    path:     /oauth2/dropbox/complete
    defaults: { _controller: AppBundle:OAuth2:dropboxComplete }

app_proxy_inbox_element:
    path:     /proxy/inbox/{encodedElementBasename}
    defaults: { _controller: AppBundle:Proxy:inboxElement }
